DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS profiles CASCADE;

DROP TABLE IF EXISTS games CASCADE;

DROP TABLE IF EXISTS publishers CASCADE;

DROP TABLE IF EXISTS libraries CASCADE;

DROP TABLE IF EXISTS reviews CASCADE;