"""empty message

Revision ID: e40ef4e087a6
Revises: 29bf7ba9674c
Create Date: 2026-06-11 09:37:25.099067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e40ef4e087a6'
down_revision: Union[str, Sequence[str], None] = '29bf7ba9674c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='gender'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='gender'),
               nullable=False)
    # ### end Alembic commands ###
